# Generated by Django 3.2.8 on 2022-05-15 21:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала приёма')),
                ('end_time', models.TimeField(verbose_name='Время конца приёма')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=100, verbose_name='Наименование услуги')),
                ('open_service', models.BooleanField(verbose_name='Наличие услуги')),
                ('start_hospitalization', models.TimeField(verbose_name='Начало времени приёма')),
                ('end_hospitalization', models.TimeField(verbose_name='Конец времени приёма')),
                ('start_button', models.TimeField(verbose_name='Начало времени работы кнопки')),
                ('end_button', models.TimeField(verbose_name='Конец времени работы кнопки')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1, verbose_name='Буква-символ отделения')),
            ],
        ),
        migrations.CreateModel(
            name='Talon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='Состояние талона')),
                ('time_registration', models.TimeField(default='00:00:00', verbose_name='Время регистрации')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service')),
                ('id_time_of_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.receipt')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='id_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.symbol'),
        ),
    ]
